### ISSUE TITLE
是否可以更新新内核版本

### ISSUE THREAD

**Issue by yt1988** [riverscn/build-openwrt-firmware#10]
ImmortalWrt 最新已经有 23.05.1，辛苦大佬适配更新一下。

或者有一些软件包都已经很老旧，比如 openwrt-passwall2 最新的是 1.21-3，系统内置的是 1.16.7。尝试过单独更新，但貌似有很多单独依赖需要处理

**Comment by riverscn** [comment]
修改这里面的分支名就行
https://github.com/riverscn/build-openwrt-firmware/blob/main/fetch_openwrt.sh
